// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ArchivesFileManagement_MVCDB
{
    public partial class SpecialCollectionsTypes
    {
        public SpecialCollectionsTypes()
        {
            SpecialCollections = new HashSet<SpecialCollections>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string TypeName { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty("Type")]
        public virtual ICollection<SpecialCollections> SpecialCollections { get; set; }
    }
}